SpongeLCA/AromaQuest

- app/views/perfumes/index.html.erb
- app/views/perfumes/show.html.erb
> show perfume

- app/assets/stylesheets/pages/_myresults.scss
ils y a quelques trucs a corriger, mais j'ai fait en forte de rattrapper le retard
> quelquels details a modifier

- app/controllers/favorites_controller.rb
- app/controllers/perfumes_controller.rb
- app/views/devise/shared/_links.html.erb
- app/views/pages/favorites.html.erb
- app/views/perfumes/index.html.erb
- app/views/perfumes/show.html.erb
- db/schema.rb
> scss et figma

- app/assets/stylesheets/components/_navbar.scss
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- db/schema.rb
Navbar faite, boostrap ajouté dans application.hmtl.erb
> navbar boostrap

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_perfumes.scss
- app/views/pages/favorites.html.erb
- app/views/perfumes/index.html.erb
- app/views/perfumes/show.html.erb
correction couleur favoris et partage, partage fonctionnel ainsi que favoris
> correction favoris et partage

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_results.scss
- app/views/results/show.html.erb
Show de results faite, scss de fait. Correction d'attribution de fonts.
> show results et son scss

- .gitignore
- app/assets/stylesheets/pages/_new.scss
- app/javascript/controllers/form_controller.js
- app/views/results/new.html.erb
- db/seeds.rb
to do : prix soit pris en compte
> Questionnaire finalisé

- app/controllers/perfumes_controller.rb
- app/views/perfumes/index.html.erb
- db/seeds.rb
filtre des notes ok dans les parfums
> flitre parfum note

- .gitignore
- Gemfile
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_perfume_details.scss
- app/views/perfumes/show.html.erb
- app/views/shared/_navbar.html.erb
- db/schema.rb
> logo navbar

- app/assets/stylesheets/pages/_myresults.scss
- app/assets/stylesheets/pages/_results.scss
- app/controllers/pages_controller.rb
- app/helpers/application_helper.rb
- app/views/pages/results.html.erb
- config/locales/fr.yml
Début front page result -dahsboard
> page result - dashboard

- app/controllers/perfumes_controller.rb
- app/controllers/reviews_controller.rb
- app/javascript/controllers/review_controller.js
- app/views/perfumes/show.html.erb
- db/seeds.rb
modification seed avec rajout des reviews automatiques
Reviews mis en place sur la show
> reviews + seed

- app/assets/stylesheets/pages/_home.scss
Léger linear gradient sur l'image de la HomePage
> Background homepage

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/pages/dashboard.html.erb
Front du Dashboard terminé, bouton "Mes achats" en prévision.
> Dashboard terminé

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_infosperso.scss
- app/assets/stylesheets/pages/_perfume_details.scss
- app/views/pages/infos.html.erb
> Infos personnelles terminées

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/pages/dashboard.html.erb
Dashboard modifications (polices) et ajouts des fausses motifs et toggles du Figma
> Dashboard modifs et toggle notifs

- app/views/pages/favorites.html.erb
- app/views/pages/results.html.erb
- app/views/perfumes/index.html.erb
- app/views/perfumes/show.html.erb
- app/views/results/show.html.erb
- config/initializers/currency.rb
Initializer pour changer l'emplacement de l'euros + views modifiées (perfume.price, unit: "€", format: "%n %u")
> Initializer currency

- app/views/results/show.html.erb
- config/initializers/currency.rb
> Correction price initializer

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
- db/schema.rb
> navbar icones

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Navbar centrée margée, homepage corrigée fautes, syntaxe et anglais
> Navbar centrée margée, homepage corrigée fautes et anglais

- app/controllers/orders_controller.rb
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- app/views/shared/_navbar.html.erb
> frais de livraison

- app/assets/stylesheets/components/_navbar.scss
Croix du bouton supprimer article centré
> Bouton supprimer panier fixé

- app/assets/stylesheets/pages/_order.scss
- app/assets/stylesheets/pages/_orders.scss
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- db/schema.rb
show order et modifs mes achats
> show order et modifs mes achats

- app/assets/stylesheets/pages/_myresults.scss
- app/assets/stylesheets/pages/_orders.scss
- app/views/pages/results.html.erb
Banner sticky modifs fonts des collapse ACHATS
> Banner sticky modifs fonts

- app/assets/stylesheets/pages/_infosperso.scss
- app/views/pages/infos.html.erb
> banniere corrigée

- app/assets/stylesheets/pages/_orders.scss
- app/views/orders/index.html.erb
collapse du index parfum comme avant
> index parfums
